<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommandLineParser" Version="2.9.1" />
  </ItemGroup>

  <Target Name="BuildNativeLib" AfterTargets="Build">
    <Message Text="Building native lib..." Importance="Normal" />
    <Exec Command="make" WorkingDirectory="$(MSBuildProjectDirectory)/../mpibridge" />
    <Message Text="Copying native lib to target directory..." Importance="Normal" />
    <Copy SourceFiles="$(MSBuildProjectDirectory)/../mpibridge/mpibridge.so" DestinationFolder="$(TargetDir)/" />
  </Target>

</Project>
